// rulesets.de.ts
// Empty German ruleset placeholder for future population
import { Rule, RuleType, Rules } from './rulesets';

export class RulesDe extends Rule {
    // This class will be filled with German rules later
}

export class GermanRules extends Rules {
    constructor() {
        super();
        // 134 Füllwörter as WeakQualifier rules
        this.addRule(new Rule(RuleType.WeakQualifier, "aber"));
        this.addRule(new Rule(RuleType.WeakQualifier, "allerdings"));
        this.addRule(new Rule(RuleType.WeakQualifier, "allgemein"));
        this.addRule(new Rule(RuleType.WeakQualifier, "also"));
        this.addRule(new Rule(RuleType.WeakQualifier, "an und für sich"));
        this.addRule(new Rule(RuleType.WeakQualifier, "anscheinend"));
        this.addRule(new Rule(RuleType.WeakQualifier, "auch"));
        this.addRule(new Rule(RuleType.WeakQualifier, "auf jeden Fall"));
        this.addRule(new Rule(RuleType.WeakQualifier, "augenscheinlich"));
        this.addRule(new Rule(RuleType.WeakQualifier, "ausdrücklich"));
        this.addRule(new Rule(RuleType.WeakQualifier, "beinahe"));
        this.addRule(new Rule(RuleType.WeakQualifier, "beispielsweise"));
        this.addRule(new Rule(RuleType.WeakQualifier, "besonders"));
        this.addRule(new Rule(RuleType.WeakQualifier, "bestimmt"));
        this.addRule(new Rule(RuleType.WeakQualifier, "beziehungsweise"));
        this.addRule(new Rule(RuleType.WeakQualifier, "bloß"));
        this.addRule(new Rule(RuleType.WeakQualifier, "da"));
        this.addRule(new Rule(RuleType.WeakQualifier, "dabei"));
        this.addRule(new Rule(RuleType.WeakQualifier, "dann"));
        this.addRule(new Rule(RuleType.WeakQualifier, "demnach"));
        this.addRule(new Rule(RuleType.WeakQualifier, "denn"));
        this.addRule(new Rule(RuleType.WeakQualifier, "dennoch"));
        this.addRule(new Rule(RuleType.WeakQualifier, "direkt"));
        this.addRule(new Rule(RuleType.WeakQualifier, "doch"));
        this.addRule(new Rule(RuleType.WeakQualifier, "durchaus"));
        this.addRule(new Rule(RuleType.WeakQualifier, "eben"));
        this.addRule(new Rule(RuleType.WeakQualifier, "ebenfalls"));
        this.addRule(new Rule(RuleType.WeakQualifier, "ebenso"));
        this.addRule(new Rule(RuleType.WeakQualifier, "eher"));
        this.addRule(new Rule(RuleType.WeakQualifier, "eigentlich"));
        this.addRule(new Rule(RuleType.WeakQualifier, "einfach"));
        this.addRule(new Rule(RuleType.WeakQualifier, "einigermaßen"));
        this.addRule(new Rule(RuleType.WeakQualifier, "einmal"));
        this.addRule(new Rule(RuleType.WeakQualifier, "entsprechend"));
        this.addRule(new Rule(RuleType.WeakQualifier, "erst"));
        this.addRule(new Rule(RuleType.WeakQualifier, "etwa"));
        this.addRule(new Rule(RuleType.WeakQualifier, "etwas"));
        this.addRule(new Rule(RuleType.WeakQualifier, "falls"));
        this.addRule(new Rule(RuleType.WeakQualifier, "fast"));
        this.addRule(new Rule(RuleType.WeakQualifier, "folglich"));
        this.addRule(new Rule(RuleType.WeakQualifier, "freilich"));
        this.addRule(new Rule(RuleType.WeakQualifier, "ganz"));
        this.addRule(new Rule(RuleType.WeakQualifier, "gänzlich"));
        this.addRule(new Rule(RuleType.WeakQualifier, "gar"));
        this.addRule(new Rule(RuleType.WeakQualifier, "gelegentlich"));
        this.addRule(new Rule(RuleType.WeakQualifier, "gemäß"));
        this.addRule(new Rule(RuleType.WeakQualifier, "genau"));
        this.addRule(new Rule(RuleType.WeakQualifier, "genommen"));
        this.addRule(new Rule(RuleType.WeakQualifier, "gewissermaßen"));
        this.addRule(new Rule(RuleType.WeakQualifier, "gleichsam"));
        this.addRule(new Rule(RuleType.WeakQualifier, "gleichzeitig"));
        this.addRule(new Rule(RuleType.WeakQualifier, "glücklicherweise"));
        this.addRule(new Rule(RuleType.WeakQualifier, "halt"));
        this.addRule(new Rule(RuleType.WeakQualifier, "häufig"));
        this.addRule(new Rule(RuleType.WeakQualifier, "höchstens"));
        this.addRule(new Rule(RuleType.WeakQualifier, "immerhin"));
        this.addRule(new Rule(RuleType.WeakQualifier, "im Grunde"));
        this.addRule(new Rule(RuleType.WeakQualifier, "insbesondere"));
        this.addRule(new Rule(RuleType.WeakQualifier, "insofern"));
        this.addRule(new Rule(RuleType.WeakQualifier, "inzwischen"));
        this.addRule(new Rule(RuleType.WeakQualifier, "irgendwie"));
        this.addRule(new Rule(RuleType.WeakQualifier, "irgendwas"));
        this.addRule(new Rule(RuleType.WeakQualifier, "ja"));
        this.addRule(new Rule(RuleType.WeakQualifier, "jedenfalls"));
        this.addRule(new Rule(RuleType.WeakQualifier, "jedoch"));
        this.addRule(new Rule(RuleType.WeakQualifier, "jetzt"));
        this.addRule(new Rule(RuleType.WeakQualifier, "kaum"));
        this.addRule(new Rule(RuleType.WeakQualifier, "keinesfalls"));
        this.addRule(new Rule(RuleType.WeakQualifier, "klar"));
        this.addRule(new Rule(RuleType.WeakQualifier, "konkret"));
        this.addRule(new Rule(RuleType.WeakQualifier, "quasi"));
        this.addRule(new Rule(RuleType.WeakQualifier, "langsam"));
        this.addRule(new Rule(RuleType.WeakQualifier, "leider"));
        this.addRule(new Rule(RuleType.WeakQualifier, "letztendlich"));
        this.addRule(new Rule(RuleType.WeakQualifier, "letztlich"));
        this.addRule(new Rule(RuleType.WeakQualifier, "mal"));
        this.addRule(new Rule(RuleType.WeakQualifier, "manchmal"));
        this.addRule(new Rule(RuleType.WeakQualifier, "mehr oder weniger"));
        this.addRule(new Rule(RuleType.WeakQualifier, "meistens"));
        this.addRule(new Rule(RuleType.WeakQualifier, "mindestens"));
        this.addRule(new Rule(RuleType.WeakQualifier, "möglicherweise"));
        this.addRule(new Rule(RuleType.WeakQualifier, "nämlich"));
        this.addRule(new Rule(RuleType.WeakQualifier, "natürlich"));
        this.addRule(new Rule(RuleType.WeakQualifier, "nicht"));
        this.addRule(new Rule(RuleType.WeakQualifier, "noch"));
        this.addRule(new Rule(RuleType.WeakQualifier, "nun"));
        this.addRule(new Rule(RuleType.WeakQualifier, "nur"));
        this.addRule(new Rule(RuleType.WeakQualifier, "offenbar"));
        this.addRule(new Rule(RuleType.WeakQualifier, "offensichtlich"));
        this.addRule(new Rule(RuleType.WeakQualifier, "oft"));
        this.addRule(new Rule(RuleType.WeakQualifier, "praktisch"));
        this.addRule(new Rule(RuleType.WeakQualifier, "regelmäßig"));
        this.addRule(new Rule(RuleType.WeakQualifier, "relativ"));
        this.addRule(new Rule(RuleType.WeakQualifier, "schließlich"));
        this.addRule(new Rule(RuleType.WeakQualifier, "schon"));
        this.addRule(new Rule(RuleType.WeakQualifier, "sehr"));
        this.addRule(new Rule(RuleType.WeakQualifier, "selbstverständlich"));
        this.addRule(new Rule(RuleType.WeakQualifier, "sicher"));
        this.addRule(new Rule(RuleType.WeakQualifier, "sicherlich"));
        this.addRule(new Rule(RuleType.WeakQualifier, "so"));
        this.addRule(new Rule(RuleType.WeakQualifier, "sozusagen"));
        this.addRule(new Rule(RuleType.WeakQualifier, "tatsächlich"));
        this.addRule(new Rule(RuleType.WeakQualifier, "total"));
        this.addRule(new Rule(RuleType.WeakQualifier, "trotzdem"));
        this.addRule(new Rule(RuleType.WeakQualifier, "überaus"));
        this.addRule(new Rule(RuleType.WeakQualifier, "überhaupt"));
        this.addRule(new Rule(RuleType.WeakQualifier, "übrigens"));
        this.addRule(new Rule(RuleType.WeakQualifier, "umso"));
        this.addRule(new Rule(RuleType.WeakQualifier, "unbedingt"));
        this.addRule(new Rule(RuleType.WeakQualifier, "ungefähr"));
        this.addRule(new Rule(RuleType.WeakQualifier, "unter Umständen"));
        this.addRule(new Rule(RuleType.WeakQualifier, "vermutlich"));
        this.addRule(new Rule(RuleType.WeakQualifier, "vielleicht"));
        this.addRule(new Rule(RuleType.WeakQualifier, "völlig"));
        this.addRule(new Rule(RuleType.WeakQualifier, "vollkommen"));
        this.addRule(new Rule(RuleType.WeakQualifier, "von daher"));
        this.addRule(new Rule(RuleType.WeakQualifier, "voraussichtlich"));
        this.addRule(new Rule(RuleType.WeakQualifier, "währenddessen"));
        this.addRule(new Rule(RuleType.WeakQualifier, "wahrscheinlich"));
        this.addRule(new Rule(RuleType.WeakQualifier, "weiterhin"));
        this.addRule(new Rule(RuleType.WeakQualifier, "weitgehend"));
        this.addRule(new Rule(RuleType.WeakQualifier, "wenigstens"));
        this.addRule(new Rule(RuleType.WeakQualifier, "wirklich"));
        this.addRule(new Rule(RuleType.WeakQualifier, "wohl"));
        this.addRule(new Rule(RuleType.WeakQualifier, "womöglich"));
        this.addRule(new Rule(RuleType.WeakQualifier, "ziemlich"));
        this.addRule(new Rule(RuleType.WeakQualifier, "zudem"));
        this.addRule(new Rule(RuleType.WeakQualifier, "zugegebenermaßen"));
        this.addRule(new Rule(RuleType.WeakQualifier, "zugleich"));
        this.addRule(new Rule(RuleType.WeakQualifier, "zumindest"));
        this.addRule(new Rule(RuleType.WeakQualifier, "zwar"));
        this.addRule(new Rule(RuleType.WeakQualifier, "zweifellos"));

        // Weasel words (German)
        this.addRule(new Rule(RuleType.WeakQualifier, "äußerst"));
        this.addRule(new Rule(RuleType.WeakQualifier, "diverse"));
        this.addRule(new Rule(RuleType.WeakQualifier, "einige"));
        this.addRule(new Rule(RuleType.WeakQualifier, "enorm"));
        this.addRule(new Rule(RuleType.WeakQualifier, "exzellent"));
        this.addRule(new Rule(RuleType.WeakQualifier, "extrem"));
        this.addRule(new Rule(RuleType.WeakQualifier, "ganz schön"));
        this.addRule(new Rule(RuleType.WeakQualifier, "gewöhnlich"));
        this.addRule(new Rule(RuleType.WeakQualifier, "größtenteils"));
        this.addRule(new Rule(RuleType.WeakQualifier, "interessant"));
        this.addRule(new Rule(RuleType.WeakQualifier, "interessanterweise"));
        this.addRule(new Rule(RuleType.WeakQualifier, "komplett"));
        this.addRule(new Rule(RuleType.WeakQualifier, "meistens"));
        this.addRule(new Rule(RuleType.WeakQualifier, "offensichtlich"));
        this.addRule(new Rule(RuleType.WeakQualifier, "riesig"));
        this.addRule(new Rule(RuleType.WeakQualifier, "sehr"));
        this.addRule(new Rule(RuleType.WeakQualifier, "selbstverständlich"));
        this.addRule(new Rule(RuleType.WeakQualifier, "signifikant"));
        this.addRule(new Rule(RuleType.WeakQualifier, "substantiell"));
        this.addRule(new Rule(RuleType.WeakQualifier, "überaus"));
        this.addRule(new Rule(RuleType.WeakQualifier, "überraschend"));
        this.addRule(new Rule(RuleType.WeakQualifier, "überraschenderweise"));
        this.addRule(new Rule(RuleType.WeakQualifier, "viel"));
        this.addRule(new Rule(RuleType.WeakQualifier, "winzig"));
        this.addRule(new Rule(RuleType.WeakQualifier, "ziemlich"));

        // Complexity rules (German)
        this.addRule(new Rule(RuleType.Complexity, "abwesend sein"));
        this.addRule(new Rule(RuleType.Complexity, "Abwesenheit"));
        this.addRule(new Rule(RuleType.Complexity, "aggregieren"));
        this.addRule(new Rule(RuleType.Complexity, "akquirieren"));
        this.addRule(new Rule(RuleType.Complexity, "akzentuieren"));
        this.addRule(new Rule(RuleType.Complexity, "alle von"));
        this.addRule(new Rule(RuleType.Complexity, "aller Wahrscheinlichkeit nach"));
        this.addRule(new Rule(RuleType.Complexity, "alles und jeder"));
        this.addRule(new Rule(RuleType.Complexity, "Als Alternative"));
        this.addRule(new Rule(RuleType.Complexity, "als Mittel"));
        this.addRule(new Rule(RuleType.Complexity, "angrenzend"));
        this.addRule(new Rule(RuleType.Complexity, "antizipieren"));
        this.addRule(new Rule(RuleType.Complexity, "anwendbar"));
        this.addRule(new Rule(RuleType.Complexity, "äquivalent"));
        this.addRule(new Rule(RuleType.Complexity, "Art von"));
        this.addRule(new Rule(RuleType.Complexity, "Assistenz"));
        this.addRule(new Rule(RuleType.Complexity, "Aufgrund der Tatsache"));
        this.addRule(new Rule(RuleType.Complexity, "aufwenden"));
        this.addRule(new Rule(RuleType.Complexity, "aufzählen"));
        this.addRule(new Rule(RuleType.Complexity, "autorisieren"));
        this.addRule(new Rule(RuleType.Complexity, "autorisiert"));
        this.addRule(new Rule(RuleType.Complexity, "beauftragen"));
        this.addRule(new Rule(RuleType.Complexity, "bemühen"));
        this.addRule(new Rule(RuleType.Complexity, "bereits bestehend"));
        this.addRule(new Rule(RuleType.Complexity, "betreffend"));
        this.addRule(new Rule(RuleType.Complexity, "bezüglich"));
        this.addRule(new Rule(RuleType.Complexity, "darlegen"));
        this.addRule(new Rule(RuleType.Complexity, "demonstrieren"));
        this.addRule(new Rule(RuleType.Complexity, "der Tatsache geschuldet"));
        this.addRule(new Rule(RuleType.Complexity, "designieren"));
        this.addRule(new Rule(RuleType.Complexity, "Dotierung"));
        this.addRule(new Rule(RuleType.Complexity, "ein bestimmtes"));
        this.addRule(new Rule(RuleType.Complexity, "ein spezifisches"));
        this.addRule(new Rule(RuleType.Complexity, "einbüßen"));
        this.addRule(new Rule(RuleType.Complexity, "eine Anzahl von"));
        this.addRule(new Rule(RuleType.Complexity, "eine Art"));
        this.addRule(new Rule(RuleType.Complexity, "einfach gesagt"));
        this.addRule(new Rule(RuleType.Complexity, "Einzelheiten"));
        this.addRule(new Rule(RuleType.Complexity, "eliminieren"));
        this.addRule(new Rule(RuleType.Complexity, "enumerieren"));
        this.addRule(new Rule(RuleType.Complexity, "erbitten"));
        this.addRule(new Rule(RuleType.Complexity, "erfolgreich absolvieren"));
        this.addRule(new Rule(RuleType.Complexity, "erhellen"));
        this.addRule(new Rule(RuleType.Complexity, "erlangen"));
        this.addRule(new Rule(RuleType.Complexity, "ermitteln"));
        this.addRule(new Rule(RuleType.Complexity, "ersichtlich"));
        this.addRule(new Rule(RuleType.Complexity, "es hat den Anschein"));
        this.addRule(new Rule(RuleType.Complexity, "es scheint"));
        this.addRule(new Rule(RuleType.Complexity, "essentiell"));
        this.addRule(new Rule(RuleType.Complexity, "evaluieren"));
        this.addRule(new Rule(RuleType.Complexity, "Evidenz"));
        this.addRule(new Rule(RuleType.Complexity, "exklusiv"));
        this.addRule(new Rule(RuleType.Complexity, "falls und wenn"));
        this.addRule(new Rule(RuleType.Complexity, "feststellen"));
        this.addRule(new Rule(RuleType.Complexity, "finalisieren"));
        this.addRule(new Rule(RuleType.Complexity, "flankieren"));
        this.addRule(new Rule(RuleType.Complexity, "folglich"));
        this.addRule(new Rule(RuleType.Complexity, "formulieren"));
        this.addRule(new Rule(RuleType.Complexity, "fortgehen"));
        this.addRule(new Rule(RuleType.Complexity, "für alle Absichten und Zwecke"));
        this.addRule(new Rule(RuleType.Complexity, "Geübtheit"));
        this.addRule(new Rule(RuleType.Complexity, "gewähren"));
        this.addRule(new Rule(RuleType.Complexity, "gewährt"));
        this.addRule(new Rule(RuleType.Complexity, "gleichwertig"));
        this.addRule(new Rule(RuleType.Complexity, "Größenordnung"));
        this.addRule(new Rule(RuleType.Complexity, "größtenteils"));
        this.addRule(new Rule(RuleType.Complexity, "hauptsächlich"));
        this.addRule(new Rule(RuleType.Complexity, "hinlänglich"));
        this.addRule(new Rule(RuleType.Complexity, "hinreichend"));
        this.addRule(new Rule(RuleType.Complexity, "im Bezug auf"));
        this.addRule(new Rule(RuleType.Complexity, "im Fall von"));
        this.addRule(new Rule(RuleType.Complexity, "im Großen und Ganzen"));
        this.addRule(new Rule(RuleType.Complexity, "in Anbetracht der Tatsache"));
        this.addRule(new Rule(RuleType.Complexity, "in bestimmten Fällen"));
        this.addRule(new Rule(RuleType.Complexity, "in bestimmten Situationen"));
        this.addRule(new Rule(RuleType.Complexity, "in Bezug auf"));
        this.addRule(new Rule(RuleType.Complexity, "In der nahen Zukunft"));
        this.addRule(new Rule(RuleType.Complexity, "in einigen Fällen"));
        this.addRule(new Rule(RuleType.Complexity, "in einigen Situationen"));
        this.addRule(new Rule(RuleType.Complexity, "in Hinsicht auf"));
        this.addRule(new Rule(RuleType.Complexity, "in lieu"));
        this.addRule(new Rule(RuleType.Complexity, "In naher Zukunft"));
        this.addRule(new Rule(RuleType.Complexity, "in Übereinstimmung mit"));
        this.addRule(new Rule(RuleType.Complexity, "in unmittelbarer Nähe"));
        this.addRule(new Rule(RuleType.Complexity, "in vielen Fällen"));
        this.addRule(new Rule(RuleType.Complexity, "Inanspruchnahme"));
        this.addRule(new Rule(RuleType.Complexity, "indes"));
        this.addRule(new Rule(RuleType.Complexity, "Indiz"));
        this.addRule(new Rule(RuleType.Complexity, "indizieren"));
        this.addRule(new Rule(RuleType.Complexity, "initiieren"));
        this.addRule(new Rule(RuleType.Complexity, "inter alia"));
        this.addRule(new Rule(RuleType.Complexity, "konsolidieren"));
        this.addRule(new Rule(RuleType.Complexity, "konstituieren"));
        this.addRule(new Rule(RuleType.Complexity, "konsultieren"));
        this.addRule(new Rule(RuleType.Complexity, "lindern"));
        this.addRule(new Rule(RuleType.Complexity, "mehrere"));
        this.addRule(new Rule(RuleType.Complexity, "meiner Meinung nach"));
        this.addRule(new Rule(RuleType.Complexity, "Methodik"));
        this.addRule(new Rule(RuleType.Complexity, "modifizieren"));
        this.addRule(new Rule(RuleType.Complexity, "nachfolgend"));
        this.addRule(new Rule(RuleType.Complexity, "negativ betreffen"));
        this.addRule(new Rule(RuleType.Complexity, "nicht oft"));
        this.addRule(new Rule(RuleType.Complexity, "nicht selten"));
        this.addRule(new Rule(RuleType.Complexity, "nicht unwahrscheinlich"));
        this.addRule(new Rule(RuleType.Complexity, "nicht viele"));
        this.addRule(new Rule(RuleType.Complexity, "nichtsdestotrotz"));
        this.addRule(new Rule(RuleType.Complexity, "Null und nichtig"));
        this.addRule(new Rule(RuleType.Complexity, "Nutzbarmachung"));
        this.addRule(new Rule(RuleType.Complexity, "objektiv"));
        this.addRule(new Rule(RuleType.Complexity, "obliegende"));
        this.addRule(new Rule(RuleType.Complexity, "offenbar"));
        this.addRule(new Rule(RuleType.Complexity, "offensichtlich"));
        this.addRule(new Rule(RuleType.Complexity, "partizipieren"));
        this.addRule(new Rule(RuleType.Complexity, "recht und billig"));
        this.addRule(new Rule(RuleType.Complexity, "Renumeration"));
        this.addRule(new Rule(RuleType.Complexity, "Residenz"));
        this.addRule(new Rule(RuleType.Complexity, "residieren"));
        this.addRule(new Rule(RuleType.Complexity, "soeben erwähnt"));
        this.addRule(new Rule(RuleType.Complexity, "sollten Sie wünschen"));
        this.addRule(new Rule(RuleType.Complexity, "statthaft"));
        this.addRule(new Rule(RuleType.Complexity, "substantiell"));
        this.addRule(new Rule(RuleType.Complexity, "tatsächlich"));
        this.addRule(new Rule(RuleType.Complexity, "tendenziell"));
        this.addRule(new Rule(RuleType.Complexity, "terminieren"));
        this.addRule(new Rule(RuleType.Complexity, "toll"));
        this.addRule(new Rule(RuleType.Complexity, "transpirieren"));
        this.addRule(new Rule(RuleType.Complexity, "Tüchtigkeit"));
        this.addRule(new Rule(RuleType.Complexity, "tunlich"));
        this.addRule(new Rule(RuleType.Complexity, "übermitteln"));
        this.addRule(new Rule(RuleType.Complexity, "überspannen"));
        this.addRule(new Rule(RuleType.Complexity, "unabänderlich"));
        this.addRule(new Rule(RuleType.Complexity, "unbestimmt"));
        this.addRule(new Rule(RuleType.Complexity, "unter Berücksichtigung"));
        this.addRule(new Rule(RuleType.Complexity, "unter der Voraussetzung"));
        this.addRule(new Rule(RuleType.Complexity, "unter Überschreitung von"));
        this.addRule(new Rule(RuleType.Complexity, "Vergleichbar mit"));
        this.addRule(new Rule(RuleType.Complexity, "verlagern"));
        this.addRule(new Rule(RuleType.Complexity, "verpflichten"));
        this.addRule(new Rule(RuleType.Complexity, "verschaffen"));
        this.addRule(new Rule(RuleType.Complexity, "verstummen"));
        this.addRule(new Rule(RuleType.Complexity, "viele verschiedene"));
        this.addRule(new Rule(RuleType.Complexity, "vollbringen"));
        this.addRule(new Rule(RuleType.Complexity, "vorantreiben"));
        this.addRule(new Rule(RuleType.Complexity, "Vorteil daraus ziehen"));
        this.addRule(new Rule(RuleType.Complexity, "vorteilhaft"));
        this.addRule(new Rule(RuleType.Complexity, "was ich sagen wollte"));
        this.addRule(new Rule(RuleType.Complexity, "was mich anbelangt"));
        this.addRule(new Rule(RuleType.Complexity, "was mich betrifft"));
        this.addRule(new Rule(RuleType.Complexity, "wie auch immer"));
        this.addRule(new Rule(RuleType.Complexity, "zahlreich"));
        this.addRule(new Rule(RuleType.Complexity, "zeitnah"));
        this.addRule(new Rule(RuleType.Complexity, "zu dieser Zeit"));
        this.addRule(new Rule(RuleType.Complexity, "zu Nutze machen"));
        this.addRule(new Rule(RuleType.Complexity, "zuallererst"));
        this.addRule(new Rule(RuleType.Complexity, "zum heutigen Zeitpunkt"));
        this.addRule(new Rule(RuleType.Complexity, "zum jetzigen Zeitpunkt"));
        this.addRule(new Rule(RuleType.Complexity, "zunutze machen"));
        this.addRule(new Rule(RuleType.Complexity, "zurechenbar"));
        this.addRule(new Rule(RuleType.Complexity, "zurückbehalten"));
        this.addRule(new Rule(RuleType.Complexity, "zurückverweisen"));

        // Redundancy rules (common German redundancies)
        this.addRule(new Rule(RuleType.Redundancy, "unbedingt erforderlich"));
        this.addRule(new Rule(RuleType.Redundancy, "absolut notwendig"));
        this.addRule(new Rule(RuleType.Redundancy, "tatsächliche Tatsachen"));
        this.addRule(new Rule(RuleType.Redundancy, "Vorausplanung"));
        this.addRule(new Rule(RuleType.Redundancy, "Vorwarnung"));
        this.addRule(new Rule(RuleType.Redundancy, "zusätzlicher Bonus"));
        this.addRule(new Rule(RuleType.Redundancy, "bejahend ja"));
        this.addRule(new Rule(RuleType.Redundancy, "Allzeit-Rekord"));
        this.addRule(new Rule(RuleType.Redundancy, "jährliches Jubiläum"));
        this.addRule(new Rule(RuleType.Redundancy, "bewaffneter Schütze"));
        this.addRule(new Rule(RuleType.Redundancy, "künstliche Prothese"));
        this.addRule(new Rule(RuleType.Redundancy, "zusammenbauen"));
        this.addRule(new Rule(RuleType.Redundancy, "zusammenfügen"));
        this.addRule(new Rule(RuleType.Redundancy, "Autobiographie des eigenen Lebens"));
        this.addRule(new Rule(RuleType.Redundancy, "grundlegende Grundlagen"));
        this.addRule(new Rule(RuleType.Redundancy, "am besten jemals"));
        this.addRule(new Rule(RuleType.Redundancy, "Biographie seines Lebens"));
        this.addRule(new Rule(RuleType.Redundancy, "kurzer Moment"));
        this.addRule(new Rule(RuleType.Redundancy, "kurze Zusammenfassung"));
        this.addRule(new Rule(RuleType.Redundancy, "brennende Glut"));
        this.addRule(new Rule(RuleType.Redundancy, "Kakophonie von Klang"));
        this.addRule(new Rule(RuleType.Redundancy, "sorgfältige Prüfung"));
        this.addRule(new Rule(RuleType.Redundancy, "aufhören und unterlassen"));
        this.addRule(new Rule(RuleType.Redundancy, "zirkulieren herum"));
        this.addRule(new Rule(RuleType.Redundancy, "einteilen in Gruppen"));
        this.addRule(new Rule(RuleType.Redundancy, "geschlossene Faust"));
        this.addRule(new Rule(RuleType.Redundancy, "zusammenarbeiten"));
        this.addRule(new Rule(RuleType.Redundancy, "kombinieren zusammen"));
        this.addRule(new Rule(RuleType.Redundancy, "konkurrieren miteinander"));
        this.addRule(new Rule(RuleType.Redundancy, "vollständig vernichten"));
        this.addRule(new Rule(RuleType.Redundancy, "komplett zerstört"));
        this.addRule(new Rule(RuleType.Redundancy, "ganz eliminieren"));
        this.addRule(new Rule(RuleType.Redundancy, "komplett gefüllt"));
        this.addRule(new Rule(RuleType.Redundancy, "vollständig umgeben"));
        this.addRule(new Rule(RuleType.Redundancy, "sich zusammen beraten"));
        this.addRule(new Rule(RuleType.Redundancy, "verbinden zusammen"));
        this.addRule(new Rule(RuleType.Redundancy, "verwirrt Zustand"));
        this.addRule(new Rule(RuleType.Redundancy, "ständig gepflegt"));
        this.addRule(new Rule(RuleType.Redundancy, "kooperieren zusammen"));
        this.addRule(new Rule(RuleType.Redundancy, "könnte möglicherweise"));
        this.addRule(new Rule(RuleType.Redundancy, "Krise Situation"));
        this.addRule(new Rule(RuleType.Redundancy, "heilender Prozess"));
        this.addRule(new Rule(RuleType.Redundancy, "aktueller Trend"));
        this.addRule(new Rule(RuleType.Redundancy, "absteigen absteigen"));
        this.addRule(new Rule(RuleType.Redundancy, "erwünschte Vorteile"));
        this.addRule(new Rule(RuleType.Redundancy, "verschiedene Arten"));
        this.addRule(new Rule(RuleType.Redundancy, "alles und jeder"));
        this.addRule(new Rule(RuleType.Redundancy, "früher zeitlich"));
        this.addRule(new Rule(RuleType.Redundancy, "beseitigen ganz"));
        this.addRule(new Rule(RuleType.Redundancy, "leeres Loch"));
        this.addRule(new Rule(RuleType.Redundancy, "beigefügt hier"));
        this.addRule(new Rule(RuleType.Redundancy, "Endresultat"));
        this.addRule(new Rule(RuleType.Redundancy, "ganz ausmerzen"));
        this.addRule(new Rule(RuleType.Redundancy, "genau gleich"));
        this.addRule(new Rule(RuleType.Redundancy, "exponierte Öffnung"));
        this.addRule(new Rule(RuleType.Redundancy, "Gesichtsmaske"));
        this.addRule(new Rule(RuleType.Redundancy, "herunterfallen"));
        this.addRule(new Rule(RuleType.Redundancy, "günstige Zustimmung"));
        this.addRule(new Rule(RuleType.Redundancy, "Klassenkameraden"));
        this.addRule(new Rule(RuleType.Redundancy, "gefüllt bis zur Kapazität"));
        this.addRule(new Rule(RuleType.Redundancy, "endgültiges Ende"));
        this.addRule(new Rule(RuleType.Redundancy, "zuallererst"));
        this.addRule(new Rule(RuleType.Redundancy, "fliegen durch die Luft"));
        this.addRule(new Rule(RuleType.Redundancy, "ausländische Importe"));
        this.addRule(new Rule(RuleType.Redundancy, "ehemaliger Absolvent"));
        this.addRule(new Rule(RuleType.Redundancy, "kostenloses Geschenk"));
        this.addRule(new Rule(RuleType.Redundancy, "gefrorenes Eis"));
        this.addRule(new Rule(RuleType.Redundancy, "voll ausgelastet"));
        this.addRule(new Rule(RuleType.Redundancy, "verschmelzen zusammen"));
        this.addRule(new Rule(RuleType.Redundancy, "zukünftige Wiederholung"));
        this.addRule(new Rule(RuleType.Redundancy, "Allgemeine Öffentlichkeit"));
        this.addRule(new Rule(RuleType.Redundancy, "wachsen in der Größe"));
        this.addRule(new Rule(RuleType.Redundancy, "illustrierte Zeichnung"));
        this.addRule(new Rule(RuleType.Redundancy, "unglaublich zu glauben"));
        this.addRule(new Rule(RuleType.Redundancy, "integrieren zusammen"));
        this.addRule(new Rule(RuleType.Redundancy, "abhängig voneinander"));
        this.addRule(new Rule(RuleType.Redundancy, "ISBN Nummer"));
        this.addRule(new Rule(RuleType.Redundancy, "kleines Baby"));
        this.addRule(new Rule(RuleType.Redundancy, "lokale Einwohner"));
        this.addRule(new Rule(RuleType.Redundancy, "zurückblicken rückblickend"));
        this.addRule(new Rule(RuleType.Redundancy, "großer Durchbruch"));
        this.addRule(new Rule(RuleType.Redundancy, "manuell mit der Hand"));
        this.addRule(new Rule(RuleType.Redundancy, "kann möglicherweise"));
        this.addRule(new Rule(RuleType.Redundancy, "treffen miteinander"));
        this.addRule(new Rule(RuleType.Redundancy, "mentale Telepathie"));
        this.addRule(new Rule(RuleType.Redundancy, "gegenseitige Zusammenarbeit"));
        this.addRule(new Rule(RuleType.Redundancy, "gegenseitig voneinander abhängig"));
        this.addRule(new Rule(RuleType.Redundancy, "Nummer eins führend"));
        this.addRule(new Rule(RuleType.Redundancy, "heimischer Lebensraum"));
        this.addRule(new Rule(RuleType.Redundancy, "natürlicher Instinkt"));
        this.addRule(new Rule(RuleType.Redundancy, "neue Innovation"));
        this.addRule(new Rule(RuleType.Redundancy, "neue Erfindung"));
        this.addRule(new Rule(RuleType.Redundancy, "Nostalgie für die Vergangenheit"));
        this.addRule(new Rule(RuleType.Redundancy, "altes Klischee"));
        this.addRule(new Rule(RuleType.Redundancy, "offener Graben"));
        this.addRule(new Rule(RuleType.Redundancy, "ursprünglich erstellt"));
        this.addRule(new Rule(RuleType.Redundancy, "überstrapaziertes Klischee"));
        this.addRule(new Rule(RuleType.Redundancy, "Paar von Zwillingen"));
        this.addRule(new Rule(RuleType.Redundancy, "vergangene Erfahrung"));
        this.addRule(new Rule(RuleType.Redundancy, "vergangene Geschichte"));
        this.addRule(new Rule(RuleType.Redundancy, "persönlicher Freund"));
        this.addRule(new Rule(RuleType.Redundancy, "persönliche Meinung"));
        this.addRule(new Rule(RuleType.Redundancy, "PIN Nummer"));
        this.addRule(new Rule(RuleType.Redundancy, "Pizza Torte"));
        this.addRule(new Rule(RuleType.Redundancy, "vorausplanen"));
        this.addRule(new Rule(RuleType.Redundancy, "polare Gegensätze"));
        this.addRule(new Rule(RuleType.Redundancy, "positive Identifikation"));
        this.addRule(new Rule(RuleType.Redundancy, "strömender Regen"));
        this.addRule(new Rule(RuleType.Redundancy, "Privat-Industrie"));
        this.addRule(new Rule(RuleType.Redundancy, "Gegenwart"));
        this.addRule(new Rule(RuleType.Redundancy, "fortfahren voraus"));
        this.addRule(new Rule(RuleType.Redundancy, "protestieren gegen"));
        this.addRule(new Rule(RuleType.Redundancy, "Rückzug zurück"));
        this.addRule(new Rule(RuleType.Redundancy, "rund in der Form"));
        this.addRule(new Rule(RuleType.Redundancy, "sicherer Hafen"));
        this.addRule(new Rule(RuleType.Redundancy, "selbst-"));
        this.addRule(new Rule(RuleType.Redundancy, "getrennt voneinander getrennt"));
        this.addRule(new Rule(RuleType.Redundancy, "teilen zusammen"));
        this.addRule(new Rule(RuleType.Redundancy, "kleine Größe"));
        this.addRule(new Rule(RuleType.Redundancy, "buchstabieren ausführlich"));
        this.addRule(new Rule(RuleType.Redundancy, "gespleißt zusammen"));
        this.addRule(new Rule(RuleType.Redundancy, "start aus"));
        this.addRule(new Rule(RuleType.Redundancy, "verbleibt noch"));
        this.addRule(new Rule(RuleType.Redundancy, "Gesamtsumme"));
        this.addRule(new Rule(RuleType.Redundancy, "umgeben von allen Seiten"));
        this.addRule(new Rule(RuleType.Redundancy, "groß in der Höhe"));
        this.addRule(new Rule(RuleType.Redundancy, "Wut Wutanfall"));
        this.addRule(new Rule(RuleType.Redundancy, "drei Uhr morgens"));
        this.addRule(new Rule(RuleType.Redundancy, "kleines bisschen"));
        this.addRule(new Rule(RuleType.Redundancy, "totale Zerstörung"));
        this.addRule(new Rule(RuleType.Redundancy, "richtige Fakten"));
        this.addRule(new Rule(RuleType.Redundancy, "wirklich aufrichtig"));
        this.addRule(new Rule(RuleType.Redundancy, "zwölf Mittag oder Mitternacht"));
        this.addRule(new Rule(RuleType.Redundancy, "ultimatives Ziel"));
        this.addRule(new Rule(RuleType.Redundancy, "unerwarteter Notfall"));
        this.addRule(new Rule(RuleType.Redundancy, "unerwartete Überraschung"));
        this.addRule(new Rule(RuleType.Redundancy, "unbeabsichtigter Fehler"));
        this.addRule(new Rule(RuleType.Redundancy, "übliches Allheilmittel"));
        this.addRule(new Rule(RuleType.Redundancy, "unbenannt anonym"));
        this.addRule(new Rule(RuleType.Redundancy, "übliches Brauch"));
        this.addRule(new Rule(RuleType.Redundancy, "schwanken hin und her"));
        this.addRule(new Rule(RuleType.Redundancy, "verschleierter Hinterhalt"));
        this.addRule(new Rule(RuleType.Redundancy, "sehr schwanger"));
        this.addRule(new Rule(RuleType.Redundancy, "sehr einzigartig"));
        this.addRule(new Rule(RuleType.Redundancy, "sichtbar für das Auge"));
        this.addRule(new Rule(RuleType.Redundancy, "warnen vorher"));
        this.addRule(new Rule(RuleType.Redundancy, "Wetterverhältnisse"));
        this.addRule(new Rule(RuleType.Redundancy, "weißer Schnee"));
        this.addRule(new Rule(RuleType.Redundancy, "aufschreiben"));
    }
}
