import { Rule, RuleType, Rules } from './rulesets';

export class GermanRules extends Rules {
    constructor() {
        super();
        // German Füllwörter as FillerWord rules
        this.addRule(new Rule(RuleType.FillerWord, "aber"));
        this.addRule(new Rule(RuleType.FillerWord, "allerdings"));
        this.addRule(new Rule(RuleType.FillerWord, "allgemein"));
        this.addRule(new Rule(RuleType.FillerWord, "also"));
        this.addRule(new Rule(RuleType.FillerWord, "an und für sich"));
        this.addRule(new Rule(RuleType.FillerWord, "anscheinend"));
        this.addRule(new Rule(RuleType.FillerWord, "auch"));
        this.addRule(new Rule(RuleType.FillerWord, "auf jeden Fall"));
        this.addRule(new Rule(RuleType.FillerWord, "augenscheinlich"));
        this.addRule(new Rule(RuleType.FillerWord, "ausdrücklich"));
        this.addRule(new Rule(RuleType.FillerWord, "beinahe"));
        this.addRule(new Rule(RuleType.FillerWord, "beispielsweise"));
        this.addRule(new Rule(RuleType.FillerWord, "besonders"));
        this.addRule(new Rule(RuleType.FillerWord, "bestimmt"));
        this.addRule(new Rule(RuleType.FillerWord, "beziehungsweise"));
        this.addRule(new Rule(RuleType.FillerWord, "bloß"));
        this.addRule(new Rule(RuleType.FillerWord, "da"));
        this.addRule(new Rule(RuleType.FillerWord, "dabei"));
        this.addRule(new Rule(RuleType.FillerWord, "dann"));
        this.addRule(new Rule(RuleType.FillerWord, "demnach"));
        this.addRule(new Rule(RuleType.FillerWord, "denn"));
        this.addRule(new Rule(RuleType.FillerWord, "dennoch"));
        this.addRule(new Rule(RuleType.FillerWord, "direkt"));
        this.addRule(new Rule(RuleType.FillerWord, "doch"));
        this.addRule(new Rule(RuleType.FillerWord, "durchaus"));
        this.addRule(new Rule(RuleType.FillerWord, "eben"));
        this.addRule(new Rule(RuleType.FillerWord, "ebenfalls"));
        this.addRule(new Rule(RuleType.FillerWord, "ebenso"));
        this.addRule(new Rule(RuleType.FillerWord, "eher"));
        this.addRule(new Rule(RuleType.FillerWord, "eigentlich"));
        this.addRule(new Rule(RuleType.FillerWord, "einfach"));
        this.addRule(new Rule(RuleType.FillerWord, "einigermaßen"));
        this.addRule(new Rule(RuleType.FillerWord, "einmal"));
        this.addRule(new Rule(RuleType.FillerWord, "entsprechend"));
        this.addRule(new Rule(RuleType.FillerWord, "erst"));
        this.addRule(new Rule(RuleType.FillerWord, "etwa"));
        this.addRule(new Rule(RuleType.FillerWord, "etwas"));
        this.addRule(new Rule(RuleType.FillerWord, "falls"));
        this.addRule(new Rule(RuleType.FillerWord, "fast"));
        this.addRule(new Rule(RuleType.FillerWord, "folglich"));
        this.addRule(new Rule(RuleType.FillerWord, "freilich"));
        this.addRule(new Rule(RuleType.FillerWord, "ganz"));
        this.addRule(new Rule(RuleType.FillerWord, "gänzlich"));
        this.addRule(new Rule(RuleType.FillerWord, "gar"));
        this.addRule(new Rule(RuleType.FillerWord, "gelegentlich"));
        this.addRule(new Rule(RuleType.FillerWord, "gemäß"));
        this.addRule(new Rule(RuleType.FillerWord, "genau"));
        this.addRule(new Rule(RuleType.FillerWord, "genommen"));
        this.addRule(new Rule(RuleType.FillerWord, "gewissermaßen"));
        this.addRule(new Rule(RuleType.FillerWord, "gleichsam"));
        this.addRule(new Rule(RuleType.FillerWord, "gleichzeitig"));
        this.addRule(new Rule(RuleType.FillerWord, "glücklicherweise"));
        this.addRule(new Rule(RuleType.FillerWord, "halt"));
        this.addRule(new Rule(RuleType.FillerWord, "häufig"));
        this.addRule(new Rule(RuleType.FillerWord, "höchstens"));
        this.addRule(new Rule(RuleType.FillerWord, "immerhin"));
        this.addRule(new Rule(RuleType.FillerWord, "im Grunde"));
        this.addRule(new Rule(RuleType.FillerWord, "insbesondere"));
        this.addRule(new Rule(RuleType.FillerWord, "insofern"));
        this.addRule(new Rule(RuleType.FillerWord, "inzwischen"));
        this.addRule(new Rule(RuleType.FillerWord, "irgendwie"));
        this.addRule(new Rule(RuleType.FillerWord, "irgendwas"));
        this.addRule(new Rule(RuleType.FillerWord, "ja"));
        this.addRule(new Rule(RuleType.FillerWord, "jedenfalls"));
        this.addRule(new Rule(RuleType.FillerWord, "jedoch"));
        this.addRule(new Rule(RuleType.FillerWord, "jetzt"));
        this.addRule(new Rule(RuleType.FillerWord, "kaum"));
        this.addRule(new Rule(RuleType.FillerWord, "keinesfalls"));
        this.addRule(new Rule(RuleType.FillerWord, "klar"));
        this.addRule(new Rule(RuleType.FillerWord, "konkret"));
        this.addRule(new Rule(RuleType.FillerWord, "quasi"));
        this.addRule(new Rule(RuleType.FillerWord, "langsam"));
        this.addRule(new Rule(RuleType.FillerWord, "leider"));
        this.addRule(new Rule(RuleType.FillerWord, "letztendlich"));
        this.addRule(new Rule(RuleType.FillerWord, "letztlich"));
        this.addRule(new Rule(RuleType.FillerWord, "mal"));
        this.addRule(new Rule(RuleType.FillerWord, "manchmal"));
        this.addRule(new Rule(RuleType.FillerWord, "mehr oder weniger"));
        this.addRule(new Rule(RuleType.FillerWord, "meistens"));
        this.addRule(new Rule(RuleType.FillerWord, "mindestens"));
        this.addRule(new Rule(RuleType.FillerWord, "möglicherweise"));
        this.addRule(new Rule(RuleType.FillerWord, "nämlich"));
        this.addRule(new Rule(RuleType.FillerWord, "natürlich"));
        this.addRule(new Rule(RuleType.FillerWord, "nicht"));
        this.addRule(new Rule(RuleType.FillerWord, "noch"));
        this.addRule(new Rule(RuleType.FillerWord, "nun"));
        this.addRule(new Rule(RuleType.FillerWord, "offenbar"));
        this.addRule(new Rule(RuleType.FillerWord, "offensichtlich"));
        this.addRule(new Rule(RuleType.FillerWord, "oft"));
        this.addRule(new Rule(RuleType.FillerWord, "praktisch"));
        this.addRule(new Rule(RuleType.FillerWord, "regelmäßig"));
        this.addRule(new Rule(RuleType.FillerWord, "relativ"));
        this.addRule(new Rule(RuleType.FillerWord, "schließlich"));
        this.addRule(new Rule(RuleType.FillerWord, "schon"));
        this.addRule(new Rule(RuleType.FillerWord, "sehr"));
        this.addRule(new Rule(RuleType.FillerWord, "selbstverständlich"));
        this.addRule(new Rule(RuleType.FillerWord, "sicher"));
        this.addRule(new Rule(RuleType.FillerWord, "sicherlich"));
        this.addRule(new Rule(RuleType.FillerWord, "so"));
        this.addRule(new Rule(RuleType.FillerWord, "sozusagen"));
        this.addRule(new Rule(RuleType.FillerWord, "tatsächlich"));
        this.addRule(new Rule(RuleType.FillerWord, "trotzdem"));
        this.addRule(new Rule(RuleType.FillerWord, "überaus"));
        this.addRule(new Rule(RuleType.FillerWord, "überhaupt"));
        this.addRule(new Rule(RuleType.FillerWord, "übrigens"));
        this.addRule(new Rule(RuleType.FillerWord, "umso"));
        this.addRule(new Rule(RuleType.FillerWord, "unbedingt"));
        this.addRule(new Rule(RuleType.FillerWord, "ungefähr"));
        this.addRule(new Rule(RuleType.FillerWord, "unter Umständen"));
        this.addRule(new Rule(RuleType.FillerWord, "vermutlich"));
        this.addRule(new Rule(RuleType.FillerWord, "vielleicht"));
        this.addRule(new Rule(RuleType.FillerWord, "völlig"));
        this.addRule(new Rule(RuleType.FillerWord, "vollkommen"));
        this.addRule(new Rule(RuleType.FillerWord, "von daher"));
        this.addRule(new Rule(RuleType.FillerWord, "voraussichtlich"));
        this.addRule(new Rule(RuleType.FillerWord, "währenddessen"));
        this.addRule(new Rule(RuleType.FillerWord, "wahrscheinlich"));
        this.addRule(new Rule(RuleType.FillerWord, "weiterhin"));
        this.addRule(new Rule(RuleType.FillerWord, "weitgehend"));
        this.addRule(new Rule(RuleType.FillerWord, "wenigstens"));
        this.addRule(new Rule(RuleType.FillerWord, "wirklich"));
        this.addRule(new Rule(RuleType.FillerWord, "wohl"));
        this.addRule(new Rule(RuleType.FillerWord, "womöglich"));
        this.addRule(new Rule(RuleType.FillerWord, "zudem"));
        this.addRule(new Rule(RuleType.FillerWord, "zugegebenermaßen"));
        this.addRule(new Rule(RuleType.FillerWord, "zugleich"));
        this.addRule(new Rule(RuleType.FillerWord, "zumindest"));
        this.addRule(new Rule(RuleType.FillerWord, "zwar"));
        this.addRule(new Rule(RuleType.FillerWord, "zweifellos"));

        // German weak qualifiers as WeakQualifier rules
        this.addRule(new Rule(RuleType.WeakQualifier, "ein bisschen")); 
        this.addRule(new Rule(RuleType.WeakQualifier, "ein wenig")); 
        this.addRule(new Rule(RuleType.WeakQualifier, "nur")); 
        this.addRule(new Rule(RuleType.WeakQualifier, "wie")); 
        this.addRule(new Rule(RuleType.WeakQualifier, "buchstäblich")); 
        this.addRule(new Rule(RuleType.WeakQualifier, "absolut")); 
        this.addRule(new Rule(RuleType.WeakQualifier, "massiv")); 
        this.addRule(new Rule(RuleType.WeakQualifier, "äußerst")); 
        this.addRule(new Rule(RuleType.WeakQualifier, "denkbar")); 
        this.addRule(new Rule(RuleType.WeakQualifier, "echt"));  
        this.addRule(new Rule(RuleType.WeakQualifier, "total"));
        this.addRule(new Rule(RuleType.WeakQualifier, "ganz und gar"));

        // Weasel words (German)
        
        this.addRule(new Rule(RuleType.WeaselWord, "diverse"));
        this.addRule(new Rule(RuleType.WeaselWord, "einige"));
        this.addRule(new Rule(RuleType.WeaselWord, "enorm"));
        this.addRule(new Rule(RuleType.WeaselWord, "exzellent"));
        this.addRule(new Rule(RuleType.WeaselWord, "extrem"));
        this.addRule(new Rule(RuleType.WeaselWord, "ganz schön"));
        this.addRule(new Rule(RuleType.WeaselWord, "gewöhnlich"));
        this.addRule(new Rule(RuleType.WeaselWord, "größtenteils"));
        this.addRule(new Rule(RuleType.WeaselWord, "interessant"));
        this.addRule(new Rule(RuleType.WeaselWord, "interessanterweise"));
        this.addRule(new Rule(RuleType.WeaselWord, "komplett"));
        this.addRule(new Rule(RuleType.WeaselWord, "meistens"));
        this.addRule(new Rule(RuleType.WeaselWord, "offensichtlich"));
        this.addRule(new Rule(RuleType.WeaselWord, "riesig"));
        this.addRule(new Rule(RuleType.WeaselWord, "selbstverständlich"));
        this.addRule(new Rule(RuleType.WeaselWord, "signifikant"));
        this.addRule(new Rule(RuleType.WeaselWord, "substantiell"));
        this.addRule(new Rule(RuleType.WeaselWord, "überaus"));
        this.addRule(new Rule(RuleType.WeaselWord, "überraschend"));
        this.addRule(new Rule(RuleType.WeaselWord, "überraschenderweise"));
        this.addRule(new Rule(RuleType.WeaselWord, "viel"));
        this.addRule(new Rule(RuleType.WeaselWord, "winzig"));
        this.addRule(new Rule(RuleType.WeaselWord, "ziemlich"));

        // Complexity rules (German)
        this.addRule(new Rule(RuleType.Complexity, "abwesend sein"));
        this.addRule(new Rule(RuleType.Complexity, "Abwesenheit"));
        this.addRule(new Rule(RuleType.Complexity, "aggregieren"));
        this.addRule(new Rule(RuleType.Complexity, "akquirieren"));
        this.addRule(new Rule(RuleType.Complexity, "akzentuieren"));
        this.addRule(new Rule(RuleType.Complexity, "alle von"));
        this.addRule(new Rule(RuleType.Complexity, "aller Wahrscheinlichkeit nach"));
        this.addRule(new Rule(RuleType.Complexity, "alles und jeder"));
        this.addRule(new Rule(RuleType.Complexity, "Als Alternative"));
        this.addRule(new Rule(RuleType.Complexity, "als Mittel"));
        this.addRule(new Rule(RuleType.Complexity, "angrenzend"));
        this.addRule(new Rule(RuleType.Complexity, "antizipieren"));
        this.addRule(new Rule(RuleType.Complexity, "anwendbar"));
        this.addRule(new Rule(RuleType.Complexity, "äquivalent"));
        this.addRule(new Rule(RuleType.Complexity, "Art von"));
        this.addRule(new Rule(RuleType.Complexity, "Assistenz"));
        this.addRule(new Rule(RuleType.Complexity, "Aufgrund der Tatsache"));
        this.addRule(new Rule(RuleType.Complexity, "aufwenden"));
        this.addRule(new Rule(RuleType.Complexity, "aufzählen"));
        this.addRule(new Rule(RuleType.Complexity, "autorisieren"));
        this.addRule(new Rule(RuleType.Complexity, "autorisiert"));
        this.addRule(new Rule(RuleType.Complexity, "beauftragen"));
        this.addRule(new Rule(RuleType.Complexity, "bemühen"));
        this.addRule(new Rule(RuleType.Complexity, "bereits bestehend"));
        this.addRule(new Rule(RuleType.Complexity, "betreffend"));
        this.addRule(new Rule(RuleType.Complexity, "bezüglich"));
        this.addRule(new Rule(RuleType.Complexity, "darlegen"));
        this.addRule(new Rule(RuleType.Complexity, "demonstrieren"));
        this.addRule(new Rule(RuleType.Complexity, "der Tatsache geschuldet"));
        this.addRule(new Rule(RuleType.Complexity, "designieren"));
        this.addRule(new Rule(RuleType.Complexity, "Dotierung"));
        this.addRule(new Rule(RuleType.Complexity, "ein bestimmtes"));
        this.addRule(new Rule(RuleType.Complexity, "ein spezifisches"));
        this.addRule(new Rule(RuleType.Complexity, "einbüßen"));
        this.addRule(new Rule(RuleType.Complexity, "eine Anzahl von"));
        this.addRule(new Rule(RuleType.Complexity, "eine Art"));
        this.addRule(new Rule(RuleType.Complexity, "einfach gesagt"));
        this.addRule(new Rule(RuleType.Complexity, "Einzelheiten"));
        this.addRule(new Rule(RuleType.Complexity, "eliminieren"));
        this.addRule(new Rule(RuleType.Complexity, "enumerieren"));
        this.addRule(new Rule(RuleType.Complexity, "erbitten"));
        this.addRule(new Rule(RuleType.Complexity, "erfolgreich absolvieren"));
        this.addRule(new Rule(RuleType.Complexity, "erhellen"));
        this.addRule(new Rule(RuleType.Complexity, "erlangen"));
        this.addRule(new Rule(RuleType.Complexity, "ermitteln"));
        this.addRule(new Rule(RuleType.Complexity, "ersichtlich"));
        this.addRule(new Rule(RuleType.Complexity, "es hat den Anschein"));
        this.addRule(new Rule(RuleType.Complexity, "es scheint"));
        this.addRule(new Rule(RuleType.Complexity, "essentiell"));
        this.addRule(new Rule(RuleType.Complexity, "evaluieren"));
        this.addRule(new Rule(RuleType.Complexity, "Evidenz"));
        this.addRule(new Rule(RuleType.Complexity, "exklusiv"));
        this.addRule(new Rule(RuleType.Complexity, "falls und wenn"));
        this.addRule(new Rule(RuleType.Complexity, "feststellen"));
        this.addRule(new Rule(RuleType.Complexity, "finalisieren"));
        this.addRule(new Rule(RuleType.Complexity, "flankieren"));
        this.addRule(new Rule(RuleType.Complexity, "folglich"));
        this.addRule(new Rule(RuleType.Complexity, "formulieren"));
        this.addRule(new Rule(RuleType.Complexity, "fortgehen"));
        this.addRule(new Rule(RuleType.Complexity, "für alle Absichten und Zwecke"));
        this.addRule(new Rule(RuleType.Complexity, "Geübtheit"));
        this.addRule(new Rule(RuleType.Complexity, "gewähren"));
        this.addRule(new Rule(RuleType.Complexity, "gewährt"));
        this.addRule(new Rule(RuleType.Complexity, "gleichwertig"));
        this.addRule(new Rule(RuleType.Complexity, "Größenordnung"));
        this.addRule(new Rule(RuleType.Complexity, "größtenteils"));
        this.addRule(new Rule(RuleType.Complexity, "hauptsächlich"));
        this.addRule(new Rule(RuleType.Complexity, "hinlänglich"));
        this.addRule(new Rule(RuleType.Complexity, "hinreichend"));
        this.addRule(new Rule(RuleType.Complexity, "im Bezug auf"));
        this.addRule(new Rule(RuleType.Complexity, "im Fall von"));
        this.addRule(new Rule(RuleType.Complexity, "im Großen und Ganzen"));
        this.addRule(new Rule(RuleType.Complexity, "in Anbetracht der Tatsache"));
        this.addRule(new Rule(RuleType.Complexity, "in bestimmten Fällen"));
        this.addRule(new Rule(RuleType.Complexity, "in bestimmten Situationen"));
        this.addRule(new Rule(RuleType.Complexity, "in Bezug auf"));
        this.addRule(new Rule(RuleType.Complexity, "In der nahen Zukunft"));
        this.addRule(new Rule(RuleType.Complexity, "in einigen Fällen"));
        this.addRule(new Rule(RuleType.Complexity, "in einigen Situationen"));
        this.addRule(new Rule(RuleType.Complexity, "in Hinsicht auf"));
        this.addRule(new Rule(RuleType.Complexity, "in lieu"));
        this.addRule(new Rule(RuleType.Complexity, "In naher Zukunft"));
        this.addRule(new Rule(RuleType.Complexity, "in Übereinstimmung mit"));
        this.addRule(new Rule(RuleType.Complexity, "in unmittelbarer Nähe"));
        this.addRule(new Rule(RuleType.Complexity, "in vielen Fällen"));
        this.addRule(new Rule(RuleType.Complexity, "Inanspruchnahme"));
        this.addRule(new Rule(RuleType.Complexity, "indes"));
        this.addRule(new Rule(RuleType.Complexity, "Indiz"));
        this.addRule(new Rule(RuleType.Complexity, "indizieren"));
        this.addRule(new Rule(RuleType.Complexity, "initiieren"));
        this.addRule(new Rule(RuleType.Complexity, "inter alia"));
        this.addRule(new Rule(RuleType.Complexity, "konsolidieren"));
        this.addRule(new Rule(RuleType.Complexity, "konstituieren"));
        this.addRule(new Rule(RuleType.Complexity, "konsultieren"));
        this.addRule(new Rule(RuleType.Complexity, "lindern"));
        this.addRule(new Rule(RuleType.Complexity, "mehrere"));
        this.addRule(new Rule(RuleType.Complexity, "meiner Meinung nach"));
        this.addRule(new Rule(RuleType.Complexity, "Methodik"));
        this.addRule(new Rule(RuleType.Complexity, "modifizieren"));
        this.addRule(new Rule(RuleType.Complexity, "nachfolgend"));
        this.addRule(new Rule(RuleType.Complexity, "negativ betreffen"));
        this.addRule(new Rule(RuleType.Complexity, "nicht oft"));
        this.addRule(new Rule(RuleType.Complexity, "nicht selten"));
        this.addRule(new Rule(RuleType.Complexity, "nicht unwahrscheinlich"));
        this.addRule(new Rule(RuleType.Complexity, "nicht viele"));
        this.addRule(new Rule(RuleType.Complexity, "nichtsdestotrotz"));
        this.addRule(new Rule(RuleType.Complexity, "Null und nichtig"));
        this.addRule(new Rule(RuleType.Complexity, "Nutzbarmachung"));
        this.addRule(new Rule(RuleType.Complexity, "objektiv"));
        this.addRule(new Rule(RuleType.Complexity, "obliegende"));
        this.addRule(new Rule(RuleType.Complexity, "offensichtlich"));
        this.addRule(new Rule(RuleType.Complexity, "partizipieren"));
        this.addRule(new Rule(RuleType.Complexity, "recht und billig"));
        this.addRule(new Rule(RuleType.Complexity, "Renumeration"));
        this.addRule(new Rule(RuleType.Complexity, "Residenz"));
        this.addRule(new Rule(RuleType.Complexity, "residieren"));
        this.addRule(new Rule(RuleType.Complexity, "soeben erwähnt"));
        this.addRule(new Rule(RuleType.Complexity, "sollten Sie wünschen"));
        this.addRule(new Rule(RuleType.Complexity, "statthaft"));
        this.addRule(new Rule(RuleType.Complexity, "substantiell"));
        this.addRule(new Rule(RuleType.Complexity, "tatsächlich"));
        this.addRule(new Rule(RuleType.Complexity, "tendenziell"));
        this.addRule(new Rule(RuleType.Complexity, "terminieren"));
        this.addRule(new Rule(RuleType.Complexity, "toll"));
        this.addRule(new Rule(RuleType.Complexity, "transpirieren"));
        this.addRule(new Rule(RuleType.Complexity, "Tüchtigkeit"));
        this.addRule(new Rule(RuleType.Complexity, "tunlich"));
        this.addRule(new Rule(RuleType.Complexity, "übermitteln"));
        this.addRule(new Rule(RuleType.Complexity, "überspannen"));
        this.addRule(new Rule(RuleType.Complexity, "unabänderlich"));
        this.addRule(new Rule(RuleType.Complexity, "unbestimmt"));
        this.addRule(new Rule(RuleType.Complexity, "unter Berücksichtigung"));
        this.addRule(new Rule(RuleType.Complexity, "unter der Voraussetzung"));
        this.addRule(new Rule(RuleType.Complexity, "unter Überschreitung von"));
        this.addRule(new Rule(RuleType.Complexity, "Vergleichbar mit"));
        this.addRule(new Rule(RuleType.Complexity, "verlagern"));
        this.addRule(new Rule(RuleType.Complexity, "verpflichten"));
        this.addRule(new Rule(RuleType.Complexity, "verschaffen"));
        this.addRule(new Rule(RuleType.Complexity, "verstummen"));
        this.addRule(new Rule(RuleType.Complexity, "viele verschiedene"));
        this.addRule(new Rule(RuleType.Complexity, "vollbringen"));
        this.addRule(new Rule(RuleType.Complexity, "vorantreiben"));
        this.addRule(new Rule(RuleType.Complexity, "Vorteil daraus ziehen"));
        this.addRule(new Rule(RuleType.Complexity, "vorteilhaft"));
        this.addRule(new Rule(RuleType.Complexity, "was ich sagen wollte"));
        this.addRule(new Rule(RuleType.Complexity, "was mich anbelangt"));
        this.addRule(new Rule(RuleType.Complexity, "was mich betrifft"));
        this.addRule(new Rule(RuleType.Complexity, "wie auch immer"));
        this.addRule(new Rule(RuleType.Complexity, "zahlreich"));
        this.addRule(new Rule(RuleType.Complexity, "zeitnah"));
        this.addRule(new Rule(RuleType.Complexity, "zu dieser Zeit"));
        this.addRule(new Rule(RuleType.Complexity, "zu Nutze machen"));
        this.addRule(new Rule(RuleType.Complexity, "zuallererst"));
        this.addRule(new Rule(RuleType.Complexity, "zum heutigen Zeitpunkt"));
        this.addRule(new Rule(RuleType.Complexity, "zum jetzigen Zeitpunkt"));
        this.addRule(new Rule(RuleType.Complexity, "zunutze machen"));
        this.addRule(new Rule(RuleType.Complexity, "zurechenbar"));
        this.addRule(new Rule(RuleType.Complexity, "zurückbehalten"));
        this.addRule(new Rule(RuleType.Complexity, "zurückverweisen"));

        // Redundancy rules 
        this.addRule(new Rule(RuleType.Redundancy, "unbedingt erforderlich"));
        this.addRule(new Rule(RuleType.Redundancy, "absolut notwendig"));
        this.addRule(new Rule(RuleType.Redundancy, "tatsächliche Tatsachen"));
        this.addRule(new Rule(RuleType.Redundancy, "Vorausplanung"));
        this.addRule(new Rule(RuleType.Redundancy, "Vorwarnung"));
        this.addRule(new Rule(RuleType.Redundancy, "zusätzlicher Bonus"));
        this.addRule(new Rule(RuleType.Redundancy, "bejahend ja"));
        this.addRule(new Rule(RuleType.Redundancy, "Allzeit-Rekord"));
        this.addRule(new Rule(RuleType.Redundancy, "jährliches Jubiläum"));
        this.addRule(new Rule(RuleType.Redundancy, "bewaffneter Schütze"));
        this.addRule(new Rule(RuleType.Redundancy, "künstliche Prothese"));
        this.addRule(new Rule(RuleType.Redundancy, "zusammenbauen"));
        this.addRule(new Rule(RuleType.Redundancy, "zusammenfügen"));
        this.addRule(new Rule(RuleType.Redundancy, "Autobiographie des eigenen Lebens"));
        this.addRule(new Rule(RuleType.Redundancy, "grundlegende Grundlagen"));
        this.addRule(new Rule(RuleType.Redundancy, "am besten jemals"));
        this.addRule(new Rule(RuleType.Redundancy, "Biographie seines Lebens"));
        this.addRule(new Rule(RuleType.Redundancy, "kurzer Moment"));
        this.addRule(new Rule(RuleType.Redundancy, "kurze Zusammenfassung"));
        this.addRule(new Rule(RuleType.Redundancy, "brennende Glut"));
        this.addRule(new Rule(RuleType.Redundancy, "Kakophonie von Klang"));
        this.addRule(new Rule(RuleType.Redundancy, "sorgfältige Prüfung"));
        this.addRule(new Rule(RuleType.Redundancy, "aufhören und unterlassen"));
        this.addRule(new Rule(RuleType.Redundancy, "zirkulieren herum"));
        this.addRule(new Rule(RuleType.Redundancy, "einteilen in Gruppen"));
        this.addRule(new Rule(RuleType.Redundancy, "geschlossene Faust"));
        this.addRule(new Rule(RuleType.Redundancy, "zusammenarbeiten"));
        this.addRule(new Rule(RuleType.Redundancy, "kombinieren zusammen"));
        this.addRule(new Rule(RuleType.Redundancy, "konkurrieren miteinander"));
        this.addRule(new Rule(RuleType.Redundancy, "vollständig vernichten"));
        this.addRule(new Rule(RuleType.Redundancy, "komplett zerstört"));
        this.addRule(new Rule(RuleType.Redundancy, "ganz eliminieren"));
        this.addRule(new Rule(RuleType.Redundancy, "komplett gefüllt"));
        this.addRule(new Rule(RuleType.Redundancy, "vollständig umgeben"));
        this.addRule(new Rule(RuleType.Redundancy, "sich zusammen beraten"));
        this.addRule(new Rule(RuleType.Redundancy, "verbinden zusammen"));
        this.addRule(new Rule(RuleType.Redundancy, "verwirrt Zustand"));
        this.addRule(new Rule(RuleType.Redundancy, "ständig gepflegt"));
        this.addRule(new Rule(RuleType.Redundancy, "kooperieren zusammen"));
        this.addRule(new Rule(RuleType.Redundancy, "könnte möglicherweise"));
        this.addRule(new Rule(RuleType.Redundancy, "Krise Situation"));
        this.addRule(new Rule(RuleType.Redundancy, "heilender Prozess"));
        this.addRule(new Rule(RuleType.Redundancy, "aktueller Trend"));
        this.addRule(new Rule(RuleType.Redundancy, "absteigen absteigen"));
        this.addRule(new Rule(RuleType.Redundancy, "erwünschte Vorteile"));
        this.addRule(new Rule(RuleType.Redundancy, "verschiedene Arten"));
        this.addRule(new Rule(RuleType.Redundancy, "alles und jeder"));
        this.addRule(new Rule(RuleType.Redundancy, "früher zeitlich"));
        this.addRule(new Rule(RuleType.Redundancy, "beseitigen ganz"));
        this.addRule(new Rule(RuleType.Redundancy, "leeres Loch"));
        this.addRule(new Rule(RuleType.Redundancy, "beigefügt hier"));
        this.addRule(new Rule(RuleType.Redundancy, "Endresultat"));
        this.addRule(new Rule(RuleType.Redundancy, "ganz ausmerzen"));
        this.addRule(new Rule(RuleType.Redundancy, "genau gleich"));
        this.addRule(new Rule(RuleType.Redundancy, "exponierte Öffnung"));
        this.addRule(new Rule(RuleType.Redundancy, "Gesichtsmaske"));
        this.addRule(new Rule(RuleType.Redundancy, "herunterfallen"));
        this.addRule(new Rule(RuleType.Redundancy, "günstige Zustimmung"));
        this.addRule(new Rule(RuleType.Redundancy, "Klassenkameraden"));
        this.addRule(new Rule(RuleType.Redundancy, "gefüllt bis zur Kapazität"));
        this.addRule(new Rule(RuleType.Redundancy, "endgültiges Ende"));
        this.addRule(new Rule(RuleType.Redundancy, "zuallererst"));
        this.addRule(new Rule(RuleType.Redundancy, "fliegen durch die Luft"));
        this.addRule(new Rule(RuleType.Redundancy, "ausländische Importe"));
        this.addRule(new Rule(RuleType.Redundancy, "ehemaliger Absolvent"));
        this.addRule(new Rule(RuleType.Redundancy, "kostenloses Geschenk"));
        this.addRule(new Rule(RuleType.Redundancy, "gefrorenes Eis"));
        this.addRule(new Rule(RuleType.Redundancy, "voll ausgelastet"));
        this.addRule(new Rule(RuleType.Redundancy, "verschmelzen zusammen"));
        this.addRule(new Rule(RuleType.Redundancy, "zukünftige Wiederholung"));
        this.addRule(new Rule(RuleType.Redundancy, "Allgemeine Öffentlichkeit"));
        this.addRule(new Rule(RuleType.Redundancy, "wachsen in der Größe"));
        this.addRule(new Rule(RuleType.Redundancy, "illustrierte Zeichnung"));
        this.addRule(new Rule(RuleType.Redundancy, "unglaublich zu glauben"));
        this.addRule(new Rule(RuleType.Redundancy, "integrieren zusammen"));
        this.addRule(new Rule(RuleType.Redundancy, "abhängig voneinander"));
        this.addRule(new Rule(RuleType.Redundancy, "ISBN Nummer"));
        this.addRule(new Rule(RuleType.Redundancy, "kleines Baby"));
        this.addRule(new Rule(RuleType.Redundancy, "lokale Einwohner"));
        this.addRule(new Rule(RuleType.Redundancy, "zurückblicken rückblickend"));
        this.addRule(new Rule(RuleType.Redundancy, "großer Durchbruch"));
        this.addRule(new Rule(RuleType.Redundancy, "manuell mit der Hand"));
        this.addRule(new Rule(RuleType.Redundancy, "kann möglicherweise"));
        this.addRule(new Rule(RuleType.Redundancy, "treffen miteinander"));
        this.addRule(new Rule(RuleType.Redundancy, "mentale Telepathie"));
        this.addRule(new Rule(RuleType.Redundancy, "gegenseitige Zusammenarbeit"));
        this.addRule(new Rule(RuleType.Redundancy, "gegenseitig voneinander abhängig"));
        this.addRule(new Rule(RuleType.Redundancy, "Nummer eins führend"));
        this.addRule(new Rule(RuleType.Redundancy, "heimischer Lebensraum"));
        this.addRule(new Rule(RuleType.Redundancy, "natürlicher Instinkt"));
        this.addRule(new Rule(RuleType.Redundancy, "neue Innovation"));
        this.addRule(new Rule(RuleType.Redundancy, "neue Erfindung"));
        this.addRule(new Rule(RuleType.Redundancy, "Nostalgie für die Vergangenheit"));
        this.addRule(new Rule(RuleType.Redundancy, "altes Klischee"));
        this.addRule(new Rule(RuleType.Redundancy, "offener Graben"));
        this.addRule(new Rule(RuleType.Redundancy, "ursprünglich erstellt"));
        this.addRule(new Rule(RuleType.Redundancy, "überstrapaziertes Klischee"));
        this.addRule(new Rule(RuleType.Redundancy, "Paar von Zwillingen"));
        this.addRule(new Rule(RuleType.Redundancy, "vergangene Erfahrung"));
        this.addRule(new Rule(RuleType.Redundancy, "vergangene Geschichte"));
        this.addRule(new Rule(RuleType.Redundancy, "persönlicher Freund"));
        this.addRule(new Rule(RuleType.Redundancy, "persönliche Meinung"));
        this.addRule(new Rule(RuleType.Redundancy, "PIN Nummer"));
        this.addRule(new Rule(RuleType.Redundancy, "Pizza Torte"));
        this.addRule(new Rule(RuleType.Redundancy, "vorausplanen"));
        this.addRule(new Rule(RuleType.Redundancy, "polare Gegensätze"));
        this.addRule(new Rule(RuleType.Redundancy, "positive Identifikation"));
        this.addRule(new Rule(RuleType.Redundancy, "strömender Regen"));
        this.addRule(new Rule(RuleType.Redundancy, "Privat-Industrie"));
        this.addRule(new Rule(RuleType.Redundancy, "Gegenwart"));
        this.addRule(new Rule(RuleType.Redundancy, "fortfahren voraus"));
        this.addRule(new Rule(RuleType.Redundancy, "protestieren gegen"));
        this.addRule(new Rule(RuleType.Redundancy, "Rückzug zurück"));
        this.addRule(new Rule(RuleType.Redundancy, "rund in der Form"));
        this.addRule(new Rule(RuleType.Redundancy, "sicherer Hafen"));
        this.addRule(new Rule(RuleType.Redundancy, "selbst-"));
        this.addRule(new Rule(RuleType.Redundancy, "getrennt voneinander getrennt"));
        this.addRule(new Rule(RuleType.Redundancy, "teilen zusammen"));
        this.addRule(new Rule(RuleType.Redundancy, "kleine Größe"));
        this.addRule(new Rule(RuleType.Redundancy, "buchstabieren ausführlich"));
        this.addRule(new Rule(RuleType.Redundancy, "gespleißt zusammen"));
        this.addRule(new Rule(RuleType.Redundancy, "start aus"));
        this.addRule(new Rule(RuleType.Redundancy, "verbleibt noch"));
        this.addRule(new Rule(RuleType.Redundancy, "Gesamtsumme"));
        this.addRule(new Rule(RuleType.Redundancy, "umgeben von allen Seiten"));
        this.addRule(new Rule(RuleType.Redundancy, "groß in der Höhe"));
        this.addRule(new Rule(RuleType.Redundancy, "Wut Wutanfall"));
        this.addRule(new Rule(RuleType.Redundancy, "drei Uhr morgens"));
        this.addRule(new Rule(RuleType.Redundancy, "kleines bisschen"));
        this.addRule(new Rule(RuleType.Redundancy, "totale Zerstörung"));
        this.addRule(new Rule(RuleType.Redundancy, "richtige Fakten"));
        this.addRule(new Rule(RuleType.Redundancy, "wirklich aufrichtig"));
        this.addRule(new Rule(RuleType.Redundancy, "zwölf Mittag oder Mitternacht"));
        this.addRule(new Rule(RuleType.Redundancy, "ultimatives Ziel"));
        this.addRule(new Rule(RuleType.Redundancy, "unerwarteter Notfall"));
        this.addRule(new Rule(RuleType.Redundancy, "unerwartete Überraschung"));
        this.addRule(new Rule(RuleType.Redundancy, "unbeabsichtigter Fehler"));
        this.addRule(new Rule(RuleType.Redundancy, "übliches Allheilmittel"));
        this.addRule(new Rule(RuleType.Redundancy, "unbenannt anonym"));
        this.addRule(new Rule(RuleType.Redundancy, "übliches Brauch"));
        this.addRule(new Rule(RuleType.Redundancy, "schwanken hin und her"));
        this.addRule(new Rule(RuleType.Redundancy, "verschleierter Hinterhalt"));
        this.addRule(new Rule(RuleType.Redundancy, "sehr schwanger"));
        this.addRule(new Rule(RuleType.Redundancy, "sehr einzigartig"));
        this.addRule(new Rule(RuleType.Redundancy, "sichtbar für das Auge"));
        this.addRule(new Rule(RuleType.Redundancy, "warnen vorher"));
        this.addRule(new Rule(RuleType.Redundancy, "Wetterverhältnisse"));
        this.addRule(new Rule(RuleType.Redundancy, "weißer Schnee"));
        this.addRule(new Rule(RuleType.Redundancy, "aufschreiben"));
     
        // Jargon and Cliché rules
        this.addRule(new Rule(RuleType.Jargon, "am Ball bleiben"));
        this.addRule(new Rule(RuleType.Jargon, "das A und O"));
        this.addRule(new Rule(RuleType.Jargon, "auf Wolke sieben"));
        this.addRule(new Rule(RuleType.Jargon, "ins kalte Wasser springen"));
        this.addRule(new Rule(RuleType.Jargon, "mit einem blauen Auge davonkommen"));
        this.addRule(new Rule(RuleType.Jargon, "auf Herz und Nieren prüfen"));
        this.addRule(new Rule(RuleType.Jargon, "auf keinen grünen Zweig kommen"));
        this.addRule(new Rule(RuleType.Jargon, "mit dem Kopf durch die Wand"));
        this.addRule(new Rule(RuleType.Jargon, "auf die lange Bank schieben"));
        this.addRule(new Rule(RuleType.Jargon, "mit allen Wassern gewaschen"));
        this.addRule(new Rule(RuleType.Jargon, "auf dem Holzweg sein"));
        this.addRule(new Rule(RuleType.Jargon, "ins Schwarze treffen"));
        this.addRule(new Rule(RuleType.Jargon, "mit offenen Karten spielen"));
        this.addRule(new Rule(RuleType.Jargon, "auf Nummer sicher gehen"));
        this.addRule(new Rule(RuleType.Jargon, "mit dem Feuer spielen"));
        this.addRule(new Rule(RuleType.Jargon, "auf den Zahn fühlen"));
        this.addRule(new Rule(RuleType.Jargon, "mit Ach und Krach"));
        this.addRule(new Rule(RuleType.Jargon, "auf Biegen und Brechen"));
        this.addRule(new Rule(RuleType.Jargon, "mit Leib und Seele"));
        this.addRule(new Rule(RuleType.Jargon, "auf Gedeih und Verderb"));
        this.addRule(new Rule(RuleType.Jargon, "Aber Hallo!"));
        this.addRule(new Rule(RuleType.Jargon, "Aber, hey…"));
        this.addRule(new Rule(RuleType.Jargon, "Aller Anfang ist schwer."));
        this.addRule(new Rule(RuleType.Jargon, "Alles klar!"));
        this.addRule(new Rule(RuleType.Jargon, "Alles nur eine Frage der Entscheidung."));
        this.addRule(new Rule(RuleType.Jargon, "Alter Schwede!"));
        this.addRule(new Rule(RuleType.Jargon, "Alternativlos"));
        this.addRule(new Rule(RuleType.Jargon, "Auf jeden Fall."));
        this.addRule(new Rule(RuleType.Jargon, "Besser spät, als nie."));
        this.addRule(new Rule(RuleType.Jargon, "Bestimmt haben Sie sich auch schon gefragt, …"));
        this.addRule(new Rule(RuleType.Jargon, "Da gibt es bestimmt eine App dafür."));
        this.addRule(new Rule(RuleType.Jargon, "Da haben sich zwei gefunden."));
        this.addRule(new Rule(RuleType.Jargon, "Da kann man nichts machen."));
        this.addRule(new Rule(RuleType.Jargon, "Da müssen Sie durch."));
        this.addRule(new Rule(RuleType.Jargon, "Da musst du durch"));
        this.addRule(new Rule(RuleType.Jargon, "Da steckt man nicht drin."));
        this.addRule(new Rule(RuleType.Jargon, "Damit kannst du mich jagen."));
        this.addRule(new Rule(RuleType.Jargon, "Damit können Sie mich jagen."));
        this.addRule(new Rule(RuleType.Jargon, "Das geht ja mal gar nicht!"));
        this.addRule(new Rule(RuleType.Jargon, "Das geht schon mal gar nicht!"));
        this.addRule(new Rule(RuleType.Jargon, "Das machen wir nach der Pandemie.."));
        this.addRule(new Rule(RuleType.Jargon, "Das ist Ansichtssache."));
        this.addRule(new Rule(RuleType.Jargon, "Das ist das Gleiche in Grün."));
        this.addRule(new Rule(RuleType.Jargon, "Das ist mal was anderes."));
        this.addRule(new Rule(RuleType.Jargon, "Das kannst du drehen und wenden, wie du willst."));
        this.addRule(new Rule(RuleType.Jargon, "Das Leben ist kein Wunschkonzert / Ponyhof"));
        this.addRule(new Rule(RuleType.Jargon, "Das Leben ist weder ein Wunschkonzert noch ein Ponyhof."));
        this.addRule(new Rule(RuleType.Jargon, "Das liegt bestimmt am Wetter."));
        this.addRule(new Rule(RuleType.Jargon, "Das stimmt eigentlich."));
        this.addRule(new Rule(RuleType.Jargon, "Das wird ein schmerzhafter Einschnitt."));
        this.addRule(new Rule(RuleType.Jargon, "Das wird schon wieder."));
        this.addRule(new Rule(RuleType.Jargon, "Dass ich das noch erleben darf."));
        this.addRule(new Rule(RuleType.Jargon, "Davon geht die Welt nicht unter."));
        this.addRule(new Rule(RuleType.Jargon, "Die Nacht ist noch jung."));
        this.addRule(new Rule(RuleType.Jargon, "Die Zeit rennt mal wieder."));
        this.addRule(new Rule(RuleType.Jargon, "Dynamisch"));
        this.addRule(new Rule(RuleType.Jargon, "Eigentlich kann ja nichts schiefgehen …"));
        this.addRule(new Rule(RuleType.Jargon, "Ende gut, alles gut."));
        this.addRule(new Rule(RuleType.Jargon, "Er sagt viel, wenn der Tag lang ist."));
        this.addRule(new Rule(RuleType.Jargon, "Erfolgsbilanz"));
        this.addRule(new Rule(RuleType.Jargon, "Ergebnisorientierung"));
        this.addRule(new Rule(RuleType.Jargon, "Es gibt keine Probleme, nur Herausforderungen!"));
        this.addRule(new Rule(RuleType.Jargon, "Früher war alles besser."));
        this.addRule(new Rule(RuleType.Jargon, "Ganz ehrlich…"));
        this.addRule(new Rule(RuleType.Jargon, "Ganz großes Kino!"));
        this.addRule(new Rule(RuleType.Jargon, "Geht nicht, gibt’s nicht."));
        this.addRule(new Rule(RuleType.Jargon, "Gleich klatscht das hier, aber kein Beifall!"));
        this.addRule(new Rule(RuleType.Jargon, "Gut, dass wir darüber gesprochen haben."));
        this.addRule(new Rule(RuleType.Jargon, "Gute Frage, nächste Frage."));
        this.addRule(new Rule(RuleType.Jargon, "Gute Frage!"));
        this.addRule(new Rule(RuleType.Jargon, "Ich für meinen Teil…"));
        this.addRule(new Rule(RuleType.Jargon, "Ich glaube, es hackt."));
        this.addRule(new Rule(RuleType.Jargon, "Ich google das mal."));
        this.addRule(new Rule(RuleType.Jargon, "Ich hab es ja schon immer gesagt."));
        this.addRule(new Rule(RuleType.Jargon, "Ich hab‘ mir sagen lassen…"));
        this.addRule(new Rule(RuleType.Jargon, "Ich habe da mal eine Frage."));
        this.addRule(new Rule(RuleType.Jargon, "Ich habe mehr Zeit als Leben."));
        this.addRule(new Rule(RuleType.Jargon, "Ich kann so nicht arbeiten."));
        this.addRule(new Rule(RuleType.Jargon, "Ich lache mich krank."));
        this.addRule(new Rule(RuleType.Jargon, "Ich melde mich."));
        this.addRule(new Rule(RuleType.Jargon, "Ich muss mal für kleine Königstiger."));
        this.addRule(new Rule(RuleType.Jargon, "Ich will ja nichts sagen, aber…"));
        this.addRule(new Rule(RuleType.Jargon, "Im Grunde genommen…"));
        this.addRule(new Rule(RuleType.Jargon, "Interessant."));
        this.addRule(new Rule(RuleType.Jargon, "Ja nee, ist klar."));
        this.addRule(new Rule(RuleType.Jargon, "Jedem das seine."));
        this.addRule(new Rule(RuleType.Jargon, "Jetzt ist es raus!"));
        this.addRule(new Rule(RuleType.Jargon, "Kann jedem mal passieren."));
        this.addRule(new Rule(RuleType.Jargon, "Kann man nichts machen."));
        this.addRule(new Rule(RuleType.Jargon, "Kein Stress!"));
        this.addRule(new Rule(RuleType.Jargon, "Komm‘ du erstmal in mein Alter."));
        this.addRule(new Rule(RuleType.Jargon, "Kommt gar nicht in die Tüte."));
        this.addRule(new Rule(RuleType.Jargon, "Kommt gar nicht in Frage."));
        this.addRule(new Rule(RuleType.Jargon, "Lass gut sein."));
        this.addRule(new Rule(RuleType.Jargon, "Mahlzeit."));
        this.addRule(new Rule(RuleType.Jargon, "Mal sehen."));
        this.addRule(new Rule(RuleType.Jargon, "Mal unter uns …"));
        this.addRule(new Rule(RuleType.Jargon, "Man sieht sich."));
        this.addRule(new Rule(RuleType.Jargon, "Man wird nicht jünger."));
        this.addRule(new Rule(RuleType.Jargon, "Mehrwert"));
        this.addRule(new Rule(RuleType.Jargon, "Meinetwegen, warum nicht?!"));
        this.addRule(new Rule(RuleType.Jargon, "Morgen ist auch noch ein Tag."));
        this.addRule(new Rule(RuleType.Jargon, "Morgens ist echt nicht meine Tageszeit."));
        this.addRule(new Rule(RuleType.Jargon, "Motiviert"));
        this.addRule(new Rule(RuleType.Jargon, "Muss ja."));
        this.addRule(new Rule(RuleType.Jargon, "Na, wer sagt’s denn."));
        this.addRule(new Rule(RuleType.Jargon, "Neue Innovation"));
        this.addRule(new Rule(RuleType.Jargon, "Nicht in diesem Ton."));
        this.addRule(new Rule(RuleType.Jargon, "Nicht wirklich."));
        this.addRule(new Rule(RuleType.Jargon, "Nichts für ungut."));
        this.addRule(new Rule(RuleType.Jargon, "Nichts hält ewig!"));
        this.addRule(new Rule(RuleType.Jargon, "Papperlapapp"));
        this.addRule(new Rule(RuleType.Jargon, "Passt schon."));
        this.addRule(new Rule(RuleType.Jargon, "Positiver Erfolg"));
        this.addRule(new Rule(RuleType.Jargon, "Proaktiv"));
        this.addRule(new Rule(RuleType.Jargon, "Prost Mahlzeit!"));
        this.addRule(new Rule(RuleType.Jargon, "Quantensprung"));
        this.addRule(new Rule(RuleType.Jargon, "Rechts ist da, wo der Daumen links ist."));
        this.addRule(new Rule(RuleType.Jargon, "Sag niemals nie."));
        this.addRule(new Rule(RuleType.Jargon, "So einfach ist das."));
        this.addRule(new Rule(RuleType.Jargon, "So haben wir nicht gewettet."));
        this.addRule(new Rule(RuleType.Jargon, "So ist das Leben."));
        this.addRule(new Rule(RuleType.Jargon, "So jung kommen wir nicht mehr zusammen."));
        this.addRule(new Rule(RuleType.Jargon, "So sieht’s aus."));
        this.addRule(new Rule(RuleType.Jargon, "So, Freunde der Sonne!"));
        this.addRule(new Rule(RuleType.Jargon, "Solange du deine Füße unter meinen Tisch stellst…"));
        this.addRule(new Rule(RuleType.Jargon, "Stell dich nicht so an."));
        this.addRule(new Rule(RuleType.Jargon, "Stimmt’s oder hab ich recht?"));
        this.addRule(new Rule(RuleType.Jargon, "Teamplayer"));
        this.addRule(new Rule(RuleType.Jargon, "Tut ja nicht weh."));
        this.addRule(new Rule(RuleType.Jargon, "Um mal ganz ehrlich zu sein …"));
        this.addRule(new Rule(RuleType.Jargon, "Umfangreiche Erfahrungen"));
        this.addRule(new Rule(RuleType.Jargon, "Und sonst so?"));
        this.addRule(new Rule(RuleType.Jargon, "Und? Wie ist das Wetter so bei euch?"));
        this.addRule(new Rule(RuleType.Jargon, "Von mir aus."));
        this.addRule(new Rule(RuleType.Jargon, "Warum nicht?!"));
        this.addRule(new Rule(RuleType.Jargon, "Was muss, das muss."));
        this.addRule(new Rule(RuleType.Jargon, "Weniger ist manchmal mehr."));
        this.addRule(new Rule(RuleType.Jargon, "Wenn Sie mich fragen …"));
        this.addRule(new Rule(RuleType.Jargon, "Wenn sie mich fragen,…"));
        this.addRule(new Rule(RuleType.Jargon, "Wer lesen kann, ist klar im Vorteil."));
        this.addRule(new Rule(RuleType.Jargon, "Wie gesagt…."));
        this.addRule(new Rule(RuleType.Jargon, "Wie schon erwähnt …."));
        this.addRule(new Rule(RuleType.Jargon, "Willkommen im Club!"));
        this.addRule(new Rule(RuleType.Jargon, "Wir sehen uns."));
        this.addRule(new Rule(RuleType.Jargon, "Wir telefonieren!"));
        this.addRule(new Rule(RuleType.Jargon, "… Punkt!"));

// ...existing
    }
}
