export interface Rulesets {
    weakQualifiers: Record<string, string>;
    jargon: Record<string, string>;
    complexity: Record<string, string>;
    redundancies: Record<string, string>;
}

export const RULESETS: Rulesets = {
    weakQualifiers:{
       "a bit": "",
       "a little": "",
       "actual": "",
       "actually": "",
       "basically": "",
       "just": "",
       "kind of": "",
       "like": "",
       "literally": "",
       "quite": "",
       "really": "",
       "simply": "",
       "sort of": "",
       "very": "",
       "somewhat": "",
    },
    jargon: {
        "at the end of the day": "",
        "boil the ocean": "",
        "double-edged sword": "",
        "going forward": "",
        "I beg to differ": "",
        "ideate": "",
        "move the needle": "",
        "moving forward": "",
        "paradigm": "",
        "paradigm shift": "",
        "rightsizing": "",
        "singing from the same hymn sheet": "",
        "touch base": "",
        "unpack": "",
    },
    complexity: {
        "as of yet": "",
        "at the present time": "",
        "close proximity": "",
        "commence": "",
        "deem": "",
        "dialogue": "",
        "due to the fact that": "",
        "endeavor": "",
        "endeavour": "",
        "enumerate": "",
        "equitable": "",
        "erroneous": "",
        "facilitate": "",
        "For all intents and purposes": "",
        "henceforth": "",
        "herewith": "",
        "honestly": "",
        "in a sense": "",
        "in lieu of": "",
        "in my humble opinion": "",
        "in order to": "",
        "in regard to": "",
        "in relation to": "",
        "in the event of": "",
        "inception": "",
        "leverage": "",
        "numerous": "",
        "per se": "",
        "pertaining to": "",
        "prior to": "",
        "subsequently": "",
        "utilise": "",
        "utilize": "",
        "of the opinion that": "",
        "with reference to": "",
        "with the exception of": "",
        "i might add": "",
        "it is interesting to note": "",
    },
    redundancies: {
        "combine together": "",
        "successfully complete": "",
        "basic fundamentals": "",
        "each and every": "",
        "in the event that": "",
        "one and the same": "",
        "critically important": "",
        "final conclusion": "",
    }
};